
# City.create(name:'East Bay', image:'http://i.imgur.com/HpBT7uF.jpg')
# City.create(name:'Monterey Bay', image:'http://i.imgur.com/xTgNLpb.jpg')
# City.create(name:'San Francisco', image:'http://i.imgur.com/5DqUUMr.jpg')
# City.create(name:'Silicon Valley', image:'http://i.imgur.com/S5aHe0z.jpg')
# City.create(name:'Wine Country', image:'http://i.imgur.com/CLLTLYO.jpg')

# # activities = ["drinks", "food", "an activity"]
# activities = ["drinks", "food"]

# activities.each do |activity|
#     Activity.create(name: activity)
# end

# sf_neighborhoods = ["Doesn't Matter", "Dogpatch", "Financial District", "Haight/Cole Valley", "Hayes Valley", "Lower Haight", "The Marina", "The Mission", "Nob Hill", "NOPA", "North Beach", "Pac Heights", "The Richmond", "Russian Hill", "SOMA", "The Sunset", "Tenderloin"]

# sf_neighborhoods.each do |neighborhood|
#   Neighborhood.create(name: neighborhood, city_id: 3)
# end

# east_bay_neighborhoods = ["Berkeley", "Doesn't Matter", "Oakland"]
# monterey_bay_neighborhoods = ["Carmel", "Doesn't Matter", "Monterey", "Santa Cruz"]
# silicon_valley_neighborhoods = ["Doesn't Matter", "Menlo Park", "Mountain View", "Palo Alto", "Palo Alto - University", "Redwood City"]
# wine_country_neighborhoods = ["Doesn't Matter", "Healdsburg", "Napa", "Sonoma", "St. Helena"]

# east_bay_neighborhoods.each do |neighborhood|
#   Neighborhood.create(name: neighborhood, city_id: 1)
# end

# monterey_bay_neighborhoods.each do |neighborhood|
#   Neighborhood.create(name: neighborhood, city_id: 2)
# end

# silicon_valley_neighborhoods.each do |neighborhood|
#   Neighborhood.create(name: neighborhood, city_id: 4)
# end

# wine_country_neighborhoods.each do |neighborhood|
#   Neighborhood.create(name: neighborhood, city_id: 5)
# end


# genres_drinks = ["something good", "cocktails", "coffee", "a dive bar", "outdoors", "wine bar"]

# genres_drinks.each do |genre|
#     Genre.create(name: genre, activity_id: 1)
# end

# genres_food = ["something yummy", "Asian", "brunch", "a burger", "a burrito", "dessert", "fancy", "quick and easy", "pizza", "a salad"]

# genres_food.each do |genre|
#     Genre.create(name: genre, activity_id: 2)
# end

Venue.create(name:'15 Romolo', link:'http://www.yelp.com/biz/15-romolo-san-francisco', address:'15 Romolo Pl', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'4505 BBQ', link:'http://www.yelp.com/biz/4505-burgers-and-bbq-san-francisco?osq=nopa+restaurants', address:'705 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'540 Club', link:'http://www.yelp.com/biz/540-club-san-francisco', address:'540 Clement St', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'840 Wine Bar & Cocktail Lounge', link:'http://www.yelp.com/biz/840-wine-bar-and-cocktail-lounge-redwood-city', address:'840 Brewster Ave', city:'Redwood City', state:'CA', zip_code:'94063')
Venue.create(name:'A16', link:'http://www.yelp.com/biz/a16-san-francisco-4', address:'2355 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Absinthe', link:'http://www.yelp.com/biz/absinthe-brasserie-and-bar-san-francisco-2', address:'398 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'ABV', link:'http://www.yelp.com/biz/abv-san-francisco-2?osq=trick+dog', address:'3174 16th St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Alembic', link:'http://www.yelp.com/biz/the-alembic-san-francisco?osq=haight+restaurants', address:'1725 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Amelie', link:'http://www.yelp.com/biz/am%C3%A9lie-san-francisco-2', address:'1754 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Americano', link:'http://www.yelp.com/biz/americano-san-francisco?osq=americano', address:'8 Mission Street', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Amie Wine Bar & Restaurant', link:'http://www.yelp.com/biz/amie-wine-bar-and-restaurant-redwood-city', address:'823 Hamilton St', city:'Redwood City', state:'CA', zip_code:'94063')
Venue.create(name:'Andytown Coffee Roasters', link:'http://www.yelp.com/biz/andytown-coffee-roasters-san-francisco', address:'3655 Lawton St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Antologia Vinoteca', link:'http://www.yelp.com/biz/antologia-vinoteca-san-francisco-2', address:'515 Broadway', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Antonio\'s Nut House', link:'http://www.yelp.com/biz/antonios-nut-house-palo-alto', address:'321 S California Ave', city:'Palo Alto', state:'CA', zip_code:'94306')
Venue.create(name:'Arizmendi Bakery', link:'http://www.yelp.com/biz/arizmendi-bakery-san-francisco', address:'1331 9th Ave', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Arlequin', link:'http://www.yelp.com/biz/arlequin-cafe-and-food-to-go-san-francisco', address:'520 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Aziza', link:'http://www.yelp.com/biz/aziza-san-francisco?osq=nopa+restaurants', address:'5800 Geary Blvd', city:'San Francisco', state:'CA', zip_code:'94121')
Venue.create(name:'B Star Bar', link:'http://www.yelp.com/biz/b-star-bar-san-francisco?osq=richmond+restaurants+dessert', address:'127 Clement St', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'b. patisserie', link:'http://www.yelp.com/biz/b-patisserie-san-francisco-2', address:'2821 California St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Bacchus Wine Bar', link:'http://www.yelp.com/biz/bacchus-wine-bar-san-francisco?page_src=related_bizes', address:'1954 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Bar Crudo', link:'http://www.yelp.com/biz/bar-crudo-san-francisco?osq=nopa+restaurants', address:'655 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Barbacco', link:'http://www.yelp.com/biz/barbacco-san-francisco', address:'220 California St', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Basik Cafe', link:'http://www.yelp.com/biz/basik-cafe-san-francisco', address:'1958 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Beacon Coffee & Pantry', link:'http://www.yelp.com/biz/beacon-coffee-and-pantry-san-francisco', address:'805 Columbus Ave', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Beretta', link:'http://www.yelp.com/biz/beretta-san-francisco?osq=best+restaurants+in+the+mission+district', address:'1199 Valencia St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Biergarten', link:'http://www.yelp.com/biz/biergarten-san-francisco', address:'424 Octavia St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Bistro Aix', link:'http://www.yelp.com/biz/bistro-aix-san-francisco?osq=marina+restaurants', address:'3340 Steiner St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Bistro Central Parc', link:'http://www.yelp.com/biz/bistro-central-parc-san-francisco?osq=nopa+restaurants', address:'560 Central Ave', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Bloodhound', link:'http://www.yelp.com/biz/bloodhound-san-francisco-2', address:'1145 Folsom St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Blue Barn Gourmet', link:'http://www.yelp.com/biz/blue-barn-gourmet-san-francisco', address:'2105 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Blue Barn Gourmet', link:'http://www.yelp.com/biz/blue-barn-gourmet-san-francisco-2', address:'2237 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Blue Bottle', link:'http://www.yelp.com/biz/blue-bottle-coffee-san-francisco-8', address:'315 Linden St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Brass Tacks', link:'http://www.yelp.com/biz/brass-tacks-san-francisco-2', address:'488 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Brenda\'s French Soul Food', link:'http://www.yelp.com/biz/brendas-french-soul-food-san-francisco', address:'652 Polk St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Brick Yard', link:'http://www.yelp.com/biz/the-brick-yard-restaurant-and-bar-san-francisco?osq=union+street+bars', address:'1787 Union St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Buckshot', link:'http://www.yelp.com/biz/buckshot-bar-and-gameroom-san-francisco-2', address:'848 Geary Blvd', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'Burma Love', link:'http://www.yelp.com/biz/burma-love-san-francisco-2', address:'211 Valencia St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Burmese Kitchen', link:'http://www.yelp.com/biz/burmese-kitchen-san-francisco-2', address:'3815 Geary Boulevard', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'Burritt Room', link:'http://www.yelp.com/biz/burritt-room-tavern-san-francisco', address:'417 Stockton St, 2nd Fl', city:'San Francisco', state:'CA', zip_code:'94108')
Venue.create(name:'Cafe Borrone', link:'http://www.yelp.com/biz/cafe-borrone-menlo-park', address:'1010 El Camino Real', city:'Menlo Park', state:'CA', zip_code:'94025')
Venue.create(name:'Cafe du Soleil', link:'http://www.yelp.com/biz/cafe-du-soleil-san-francisco', address:'200 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Cafe Du Soleil', link:'http://www.yelp.com/biz/cafe-du-soleil-san-francisco-4?osq=best+salad', address:'345 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Chambers', link:'http://www.yelp.com/biz/chambers-san-francisco-3', address:'601 Eddy St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Chantal Guillon Macarons', link:'http://www.yelp.com/biz/chantal-guillon-san-francisco?osq=soma+restaurants', address:'1309 Howard St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Cheese Board Pizza', link:'http://www.yelp.com/biz/cheese-board-pizza-berkeley', address:'1512 Shattuck Ave', city:'Berkeley', state:'CA', zip_code:'94709')
Venue.create(name:'Chez Maman', link:'http://www.yelp.com/biz/chez-maman-west-san-francisco-2', address:'401 Gough St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Chez Panisse', link:'http://www.yelp.com/biz/chez-panisse-berkeley', address:'1517 Shattuck Ave', city:'Berkeley', state:'CA', zip_code:'94709')
Venue.create(name:'Chili Pies', link:'http://www.yelp.com/biz/chile-pies-and-ice-cream-san-francisco?osq=chili+pies', address:'601 Baker St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Club Waziema', link:'http://www.yelp.com/biz/club-waziema-san-francisco', address:'543 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Coffee Bar', link:'http://www.yelp.com/biz/coffee-bar-san-francisco-2', address:'101 Montgomery St', city:'San Francisco', state:'CA', zip_code:'94104')
Venue.create(name:'Commonwealth', link:'http://www.yelp.com/biz/commonwealth-san-francisco', address:'2224 Mission St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Cotogna', link:'http://www.yelp.com/biz/cotogna-san-francisco', address:'490 Pacific Ave', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Coupa Cafe', link:'http://www.yelp.com/biz/coupa-caf%C3%A9-palo-alto-3', address:'538 Ramona St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Darwin Cafe', link:'http://www.yelp.com/biz/darwin-cafe-san-francisco?osq=soma+restaurants', address:'212 Ritch St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Delarosa', link:'http://www.yelp.com/biz/delarosa-san-francisco', address:'2175 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Devils Acre', link:'http://www.yelp.com/biz/the-devils-acre-san-francisco', address:'256 Columbus', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Dogpatch Saloon', link:'http://www.yelp.com/biz/dogpatch-saloon-san-francisco-3', address:'2496 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Dogpatch Wine Works', link:'http://www.yelp.com/biz/dogpatch-wineworks-san-francisco', address:'2455 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Dottie\'s True Blue Cafe', link:'http://www.yelp.com/biz/dotties-true-blue-cafe-san-francisco', address:'28 6th St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Edinburgh Castle', link:'http://www.yelp.com/biz/edinburgh-castle-pub-san-francisco-2', address:'950 Geary St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'El Farolito', link:'http://www.yelp.com/biz/el-farolito-san-francisco-2?osq=best+restaurants+in+the+mission+district', address:'2779 Mission St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'El Techo de Lolinda', link:'http://www.yelp.com/biz/el-techo-de-lolinda-san-francisco-2?osq=mission+restaurants', address:'2518 Mission St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'El Tesoro Taqueria & Grill', link:'http://www.yelp.com/biz/el-tesoro-taqueria-and-grill-san-francisco', address:'599 O\'Farrell St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Escape From New York', link:'http://www.yelp.com/biz/escape-from-new-york-pizza-san-francisco-3', address:'1737 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Evolution Fresh', link:'http://www.yelp.com/biz/evolution-fresh-san-francisco', address:'2201 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Evvia Estiatorio', link:'http://www.yelp.com/biz/evvia-estiatorio-palo-alto', address:'420 Emerson St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Farmstead at Long Meadow Ranch', link:'http://www.yelp.com/biz/farmstead-at-long-meadow-ranch-saint-helena', address:'738 Main St', city:'St. Helena', state:'CA', zip_code:'94574')
Venue.create(name:'Fig & Thistle', link:'http://www.yelp.com/biz/fig-and-thistle-san-francisco-2', address:'313 Ivy St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Fireside Bar', link:'http://www.yelp.com/biz/fireside-bar-san-francisco', address:'603 Irving St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Flour & Co', link:'http://www.yelp.com/biz/flour-and-co-san-francisco-3?osq=nob+hill+restaurants', address:'1030 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Flour + Water', link:'http://www.yelp.com/biz/flour-water-san-francisco', address:'2401 Harrison St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Flywheel Coffee Roasters', link:'http://www.yelp.com/biz/flywheel-coffee-roasters-san-francisco', address:'672 Stanyan St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Foreign Cinema', link:'http://www.yelp.com/biz/foreign-cinema-san-francisco', address:'2534 Mission St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Four Barrel', link:'http://www.yelp.com/biz/four-barrel-coffee-san-francisco?osq=best+restaurants+in+the+mission+district', address:'375 Valencia St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Frances', link:'http://www.yelp.com/biz/frances-san-francisco', address:'3870 17th St.', city:'San Francisco', state:'CA', zip_code:'94114')
Venue.create(name:'Fresca', link:'http://www.yelp.com/biz/fresca-san-francisco-4', address:'2114 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Fresh Brew', link:'http://www.yelp.com/biz/fresh-brew-coffee-san-francisco', address:'882 Bush St', city:'San Francisco', state:'CA', zip_code:'94108')
Venue.create(name:'Garaje', link:'http://www.yelp.com/biz/garaje-san-francisco', address:'475 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Gialina', link:'http://www.yelp.com/biz/gialina-pizzeria-san-francisco', address:'2842 Diamond St', city:'San Francisco', state:'CA', zip_code:'94131')
Venue.create(name:'Gioia Pizzeria', link:'http://www.yelp.com/biz/gioia-pizzeria-san-francisco', address:'2240 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Gordo Taqueria', link:'http://www.yelp.com/biz/gordo-taqueria-san-francisco-2', address:'2252 Clement St', city:'San Francisco', state:'CA', zip_code:'94121')
Venue.create(name:'Gott\'s Roadside', link:'http://www.yelp.com/biz/gotts-roadside-saint-helena-2', address:'933 Main St', city:'St. Helena', state:'CA', zip_code:'94574')
Venue.create(name:'Gott\'s Roadside', link:'http://www.yelp.com/biz/gotts-roadside-san-francisco-2', address:'1 Ferry Bldg', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Gracias Madre', link:'http://www.yelp.com/biz/gracias-madre-san-francisco?osq=mission+restaurants', address:'2211 Mission St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Great China', link:'http://www.yelp.com/biz/great-china-berkeley', address:'2190 Bancroft Way', city:'Berkeley', state:'CA', zip_code:'94704')
Venue.create(name:'Green Chili Kitchen', link:'http://www.yelp.com/biz/green-chile-kitchen-san-francisco?osq=nopa+restaurants', address:'1801 McAllister St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Hog Island Oyster Co', link:'http://www.yelp.com/biz/hog-island-oyster-co-napa', address:'610 1st St', city:'Napa', state:'CA', zip_code:'94559')
Venue.create(name:'Hooker\'s Sweet Treats', link:'http://www.yelp.com/biz/hookers-sweet-treats-san-francisco', address:'442 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'House of Thai 2', link:'http://www.yelp.com/biz/house-of-thai-2-san-francisco?osq=lower+haight+restaurants', address:'494 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Humphry Slocombe', link:'http://www.yelp.com/biz/humphry-slocombe-ice-cream-san-francisco', address:'2790A Harrison St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'InoVino', link:'http://www.yelp.com/biz/inovino-san-francisco', address:'108B Carl St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Jamber', link:'http://www.yelp.com/biz/jamber-san-francisco', address:'858 Folsom St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Jane', link:'http://www.yelp.com/biz/jane-on-fillmore-san-francisco', address:'2123 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Jenny\'s Burgers', link:'http://www.yelp.com/biz/jennys-burgers-san-francisco', address:'1233 9th Ave', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Joanie\'s Cafe', link:'http://www.yelp.com/biz/joanies-caf%C3%A9-palo-alto-2', address:'405 S California Ave', city:'Palo Alto', state:'CA', zip_code:'94306')
Venue.create(name:'Jones', link:'http://www.yelp.com/biz/jones-san-francisco-3', address:'620 Jones St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Judalicious', link:'http://www.yelp.com/biz/judahlicious-san-francisco', address:'3906 Judah St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Judy\'s Cafe', link:'http://www.yelp.com/biz/judys-homestyle-cafe-san-francisco', address:'2268 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Just For You Cafe', link:'http://www.yelp.com/biz/just-for-you-cafe-san-francisco?osq=dogpatch+restaurants', address:'732 22nd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Kate\'s Kitchen', link:'http://www.yelp.com/biz/kates-kitchen-san-francisco?osq=upper+haight+restaurants', address:'471 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Kezar Pub', link:'http://www.yelp.com/biz/kezar-pub-san-francisco-2', address:'770 Stanyan St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Kokkari Estiatorio', link:'http://www.yelp.com/biz/kokkari-estiatorio-san-francisco', address:'200 Jackson St', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Kusakabe', link:'http://www.yelp.com/biz/kusakabe-san-francisco', address:'584 Washington St', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'La Stazione Coffee', link:'http://www.yelp.com/biz/la-stazione-coffee-and-wine-bar-san-francisco?osq=dogpatch+restaurants', address:'701 Pennsylvania Ave', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'La Taqueria', link:'http://www.yelp.com/biz/la-taqueria-san-francisco-2', address:'2889 Mission St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Le Marais Bakery', link:'http://www.yelp.com/biz/le-marais-san-francisco', address:'2066 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Le Mediterranee', link:'http://www.yelp.com/biz/la-m%C3%A9diterran%C3%A9e-san-francisco-3', address:'2210 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Leopold\'s', link:'http://www.yelp.com/biz/leopolds-san-francisco-2', address:'2400 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Lers Ros Thai', link:'http://www.yelp.com/biz/lers-ros-thai-san-francisco', address:'730 Larkin St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Lion Pub', link:'http://www.yelp.com/biz/lion-pub-san-francisco', address:'2062 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Liquid Gold', link:'http://www.yelp.com/biz/liquid-gold-san-francisco', address:'1040 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Little Star Pizza', link:'http://www.yelp.com/biz/little-star-pizza-san-francisco?osq=nopa+restaurants', address:'846 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Local Edition', link:'http://www.yelp.com/biz/local-edition-san-francisco', address:'691 Market St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Lolo', link:'http://www.yelp.com/biz/lol%C3%B3-san-francisco-4', address:'974 Valencia St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Long Bridge Pizza', link:'http://www.yelp.com/biz/long-bridge-pizza-company-san-francisco?osq=dogpatch+restaurants', address:'2347 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Lucca Delicatessen', link:'http://www.yelp.com/biz/lucca-delicatessen-san-francisco', address:'2120 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'LYFE Kitchen', link:'http://www.yelp.com/biz/lyfe-kitchen-palo-alto', address:'167 Hamilton Ave', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Mad Dog in the Fog', link:'http://www.yelp.com/biz/mad-dog-in-the-fog-san-francisco', address:'530 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Magnolia Pub & Brewery', link:'http://www.yelp.com/biz/magnolia-pub-and-brewery-san-francisco', address:'1398 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Mama\'s', link:'http://www.yelp.com/biz/mamas-on-washington-square-san-francisco', address:'1701 Stockton St', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Marlowe', link:'http://www.yelp.com/biz/marlowe-san-francisco-2?osq=soma+restaurants', address:'500 Brannan St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Martin\'s West Gastropub', link:'http://www.yelp.com/biz/martins-west-gastropub-redwood-city', address:'831 Main St', city:'Redwood City', state:'CA', zip_code:'94063')
Venue.create(name:'Mason Pacific', link:'http://www.yelp.com/biz/mason-pacific-san-francisco?osq=nob+hill+restaurants', address:'1358 Mason St', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Mauna Loa', link:'http://www.yelp.com/biz/mauna-loa-club-san-francisco', address:'3009 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Maven', link:'http://www.yelp.com/biz/maven-san-francisco?osq=upper+haight+restaurants', address:'598 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Mission Bowling Club', link:'http://www.yelp.com/biz/mission-bowling-club-san-francisco', address:'3176 17th St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Mission Cheese', link:'http://www.yelp.com/biz/mission-cheese-san-francisco?osq=best+restaurants+in+the+mission+district', address:'736 Valencia St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Mixt Greens', link:'http://www.yelp.com/biz/mixt-greens-san-francisco', address:'120 Sansome St', city:'San Francisco', state:'CA', zip_code:'94104')
Venue.create(name:'Molinari Delicatessen', link:'http://www.yelp.com/biz/molinari-delicatessen-san-francisco', address:'373 Columbus Ave', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Mourad', link:'http://www.yelp.com/biz/mourad-restaurant-san-francisco?osq=soma+restaurants', address:'140 New Montgomery St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Mr. and Mrs. Miscellaneous', link:'http://www.yelp.com/biz/mr-and-mrs-miscellaneous-san-francisco?osq=dogpatch+restaurants', address:'699 22nd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Mr. Holmes Bakehouse', link:'http://www.yelp.com/biz/mr-holmes-bakehouse-san-francisco', address:'1042 Larkin St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Namu Gaji', link:'http://www.yelp.com/biz/namu-gaji-san-francisco', address:'499 Dolores St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Napa Valley Coffee Roasting Co', link:'http://www.yelp.com/biz/napa-valley-coffee-roasting-co-saint-helena', address:'1400 Oak Ave', city:'St. Helena', state:'CA', zip_code:'94574')
Venue.create(name:'Nectar Wine Lounge', link:'http://www.yelp.com/biz/nectar-wine-lounge-san-francisco', address:'3330 Steiner St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Nob HIll Cafe', link:'http://www.yelp.com/biz/nob-hill-cafe-san-francisco', address:'1152 Taylor St', city:'San Francisco', state:'CA', zip_code:'94108')
Venue.create(name:'Nob Hill Grille', link:'http://www.yelp.com/biz/nob-hill-grille-san-francisco?osq=best+burgers+and+beer', address:'969 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Nopa', link:'http://www.yelp.com/biz/nopa-san-francisco', address:'560 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Nopalito', link:'http://www.yelp.com/biz/nopalito-san-francisco-3', address:'1224 9th Ave', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Nourish Cafe', link:'http://www.yelp.com/biz/nourish-cafe-san-francisco', address:'189 6th Ave', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'Okoze Sushi', link:'http://www.yelp.com/biz/okoze-sushi-san-francisco', address:'1207 Union St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Old Mandarin Islamic Restaurant', link:'http://www.yelp.com/biz/old-mandarin-islamic-restaurant-san-francisco', address:'3132 Vicente St', city:'San Francisco', state:'CA', zip_code:'94116')
Venue.create(name:'Olea', link:'http://www.yelp.com/biz/olea-san-francisco?osq=verbena', address:'1494 California St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Oren\'s Hummus Shop', link:'http://www.yelp.com/biz/orens-hummus-shop-palo-alto', address:'261 University Ave', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Otoro Sushi', link:'http://www.yelp.com/biz/o-toro-sushi-san-francisco', address:'205 Oak St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Outerlands', link:'http://www.yelp.com/biz/outerlands-san-francisco', address:'4001 Judah St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Pabu', link:'http://www.yelp.com/biz/pabu-san-francisco', address:'101 California St', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Pacific Cafe', link:'http://www.yelp.com/biz/pacific-cafe-san-francisco?osq=richmond+restaurants+seafood', address:'7000 Geary Blvd', city:'San Francisco', state:'CA', zip_code:'94121')
Venue.create(name:'Pacific Catch', link:'http://www.yelp.com/biz/pacific-catch-san-francisco?osq=marina+restaurants', address:'2027 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Padrecito', link:'http://www.yelp.com/biz/padrecito-san-francisco', address:'901 Cole St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Palmyra', link:'http://www.yelp.com/biz/palmyra-san-francisco?osq=lower+haight+restaurants', address:'700 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Papalote', link:'http://www.yelp.com/biz/papalote-mexican-grill-san-francisco-2?osq=nopa+restaurants', address:'1777 Fulton St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Papito', link:'http://www.yelp.com/biz/papito-hayes-san-francisco', address:'425 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Park Tavern', link:'http://www.yelp.com/biz/park-tavern-san-francisco', address:'1652 Stockton St', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Pastis', link:'http://www.yelp.com/biz/pastis-palo-alto', address:'447 S California Ave', city:'Palo Alto', state:'CA', zip_code:'94306')
Venue.create(name:'Patxi\'s Pizza', link:'http://www.yelp.com/biz/patxis-pizza-san-francisco-2', address:'511 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Patxi\'s Pizza', link:'http://www.yelp.com/biz/patxis-pizza-palo-alto', address:'441 Emerson St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Pearl\'s Deluxe Burgers', link:'http://www.yelp.com/biz/pearls-deluxe-burgers-san-francisco-3', address:'708 Post St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Perbacco', link:'http://www.yelp.com/biz/perbacco-san-francisco', address:'230 California St', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Philz Coffee', link:'http://www.yelp.com/biz/philz-coffee-san-francisco-8', address:'399 Golden Gate Ave', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Piccino', link:'http://www.yelp.com/biz/piccino-san-francisco', address:'1001 Minnesota St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Picnic on Third', link:'http://www.yelp.com/biz/picnic-on-third-san-francisco', address:'493 3rd St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Pizza Orgasmica', link:'http://www.yelp.com/biz/pizza-orgasmica-and-brewing-co-san-francisco', address:'2 Embarcadero Ctr', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Pizzeria Delfina', link:'http://www.yelp.com/biz/pizzeria-delfina-palo-alto', address:'651 Emerson St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Pizzeria Delfina', link:'http://www.yelp.com/biz/pizzeria-delfina-san-francisco-3', address:'2406 California St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Pizzetta 211', link:'http://www.yelp.com/biz/pizzetta-211-san-francisco', address:'211 23rd Ave', city:'San Francisco', state:'CA', zip_code:'94121')
Venue.create(name:'Place Pigalle', link:'http://www.yelp.com/biz/place-pigalle-san-francisco', address:'520 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Pluto\'s', link:'http://www.yelp.com/biz/plutos-san-francisco-3', address:'627 Irving St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'PRESS', link:'http://www.yelp.com/biz/press-st-helena', address:'587 St Helena Hwy S', city:'St. Helena', state:'CA', zip_code:'94574')
Venue.create(name:'Press Club', link:'http://www.yelp.com/biz/press-club-san-francisco', address:'20 Yerba Buena Ln', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Quince', link:'http://www.yelp.com/biz/quince-san-francisco', address:'470 Pacific Ave', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Ragazza', link:'http://www.yelp.com/biz/ragazza-san-francisco?osq=lower+haight+restaurants', address:'311 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Range', link:'http://www.yelp.com/biz/range-restaurant-san-francisco?osq=best+restaurants+in+the+mission+district', address:'842 Valencia St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Red Door Cafe', link:'http://www.yelp.com/biz/red-door-cafe-san-francisco-3', address:'1608 Bush St', city:'San Francisco', state:'CA', zip_code:'94108')
Venue.create(name:'Red Door Coffee', link:'http://www.yelp.com/biz/red-door-coffee-san-francisco-2', address:'111 Minna St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Reposado', link:'http://www.yelp.com/biz/reposado-palo-alto', address:'236 Hamilton Ave', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Rich Table', link:'http://www.yelp.com/biz/rich-table-san-francisco', address:'199 Gough St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Rickhouse', link:'http://www.yelp.com/biz/rickhouse-san-francisco?osq=best+bar+financial+district', address:'246 Kearny St', city:'San Francisco', state:'CA', zip_code:'94108')
Venue.create(name:'Roam Artisan Burgers', link:'http://www.yelp.com/biz/roam-artisan-burgers-san-francisco-3', address:'1923 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Rosamunde', link:'http://www.yelp.com/biz/rosamunde-sausage-grill-san-francisco', address:'545 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Rosewood Sand Hill', link:'http://www.yelp.com/biz/rosewood-sand-hill-menlo-park', address:'2825 Sand Hill Rd', city:'Menlo Park', state:'CA', zip_code:'94025')
Venue.create(name:'Rye', link:'http://www.yelp.com/biz/rye-san-francisco?osq=nob+hill+bars', address:'688 Geary St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Saigon Sandwich', link:'http://www.yelp.com/biz/saigon-sandwich-san-francisco', address:'560 Larkin St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Saint Frank Coffee', link:'http://www.yelp.com/biz/saint-frank-coffee-san-francisco-2', address:'2340 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'San Tung Chinese Restaurant', link:'http://www.yelp.com/biz/san-tung-chinese-restaurant-san-francisco', address:'1031 Irving St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Schubert\'s Bakery', link:'http://www.yelp.com/biz/schuberts-bakery-san-francisco', address:'521 Clement St', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'Serpentine', link:'http://www.yelp.com/biz/serpentine-san-francisco', address:'2495 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Seven Hills', link:'http://www.yelp.com/biz/seven-hills-san-francisco?osq=nob+hill+restaurants', address:'1550 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Siam Lotus Thai Cuisine', link:'http://www.yelp.com/biz/siam-lotus-thai-cuisine-san-francisco', address:'1705 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Slanted Door', link:'http://www.yelp.com/biz/the-slanted-door-san-francisco', address:'1 Ferry Bldg', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'Smitten Ice Cream', link:'http://www.yelp.com/biz/smitten-ice-cream-san-francisco-3', address:'432 Octavia St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Southside Spirit House', link:'http://www.yelp.com/biz/southside-spirit-house-san-francisco?osq=soma+restaurants', address:'575 Howard St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Souvla', link:'http://www.yelp.com/biz/souvla-san-francisco', address:'517 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Sparrow', link:'http://www.yelp.com/biz/sparrow-bar-and-kitchen-san-francisco', address:'1640 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'SPQR', link:'http://www.yelp.com/biz/spqr-san-francisco', address:'1911 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Sprout', link:'http://www.yelp.com/biz/sprout-cafe-palo-alto', address:'168 University Ave', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Spruce', link:'http://www.yelp.com/biz/spruce-san-francisco', address:'3640 Sacramento St', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'Stones Throw', link:'http://www.yelp.com/biz/stones-throw-san-francisco-2', address:'1896 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Street Taco', link:'http://www.yelp.com/biz/street-taco-san-francisco', address:'1607 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Sunrise Deli', link:'http://www.yelp.com/biz/sunrise-deli-san-francisco-4', address:'1671 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Super Duper', link:'http://www.yelp.com/biz/super-duper-burgers-san-francisco-5', address:'2200 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'suppenkuche', link:'http://www.yelp.com/biz/suppenk%C3%BCche-san-francisco-2', address:'525 Laguna St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'SusieCakes', link:'http://www.yelp.com/biz/susiecakes-san-francisco', address:'2109 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Sweet Woodruff', link:'http://www.yelp.com/biz/sweet-woodruff-san-francisco?osq=nob+hill+restaurants', address:'798 Sutter St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Swensen\'s Ice Cream', link:'http://www.yelp.com/biz/swensens-ice-cream-san-francisco', address:'1999 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Tamarine Restaurant', link:'http://www.yelp.com/biz/tamarine-restaurant-palo-alto', address:'546 University Ave', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Tartine', link:'http://www.yelp.com/biz/tartine-bakery-and-cafe-san-francisco', address:'600 Guerrero St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Tempest', link:'http://www.yelp.com/biz/tempest-san-francisco', address:'431 Natoma St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'The Buccaneer', link:'http://www.yelp.com/biz/the-buccaneer-san-francisco', address:'2155 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'The Dutch Goose', link:'http://www.yelp.com/biz/the-dutch-goose-menlo-park-2', address:'3567 Alameda de Las Pulgas', city:'Menlo Park', state:'CA', zip_code:'94025')
Venue.create(name:'The Hidden Vine', link:'http://www.yelp.com/biz/the-hidden-vine-san-francisco?osq=best+bar+financial+district', address:'408 Merchant St', city:'San Francisco', state:'CA', zip_code:'94111')
Venue.create(name:'The House', link:'http://www.yelp.com/biz/the-house-san-francisco', address:'1230 Grant Ave', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'The Ice Cream Bar', link:'http://www.yelp.com/biz/the-ice-cream-bar-san-francisco', address:'815 Cole St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'The Interval at Long Now', link:'http://www.yelp.com/biz/the-interval-at-long-now-san-francisco', address:'2 Marina Blvd, Bldg A', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'The Mill', link:'http://www.yelp.com/biz/the-mill-san-francisco', address:'736 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'The Old Pro', link:'http://www.yelp.com/biz/the-old-pro-palo-alto', address:'541 Ramona St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'The Page', link:'http://www.yelp.com/biz/the-page-san-francisco', address:'298 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'The Prolific Oven', link:'http://www.yelp.com/biz/the-prolific-oven-palo-alto', address:'550 Waverley St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'The Ramp', link:'http://www.yelp.com/biz/the-ramp-san-francisco?osq=dogpatch+restaurants', address:'855 Terry Francois St', city:'San Francisco', state:'CA', zip_code:'94158')
Venue.create(name:'The Richmond', link:'http://www.yelp.com/biz/the-richmond-san-francisco?osq=nopa+restaurants', address:'615 Balboa St', city:'San Francisco', state:'CA', zip_code:'94118')
Venue.create(name:'The Wine Room', link:'http://www.yelp.com/biz/the-wine-room-palo-alto', address:'520 Ramona St', city:'Palo Alto', state:'CA', zip_code:'94301')
Venue.create(name:'Three Twins Ice Cream', link:'http://www.yelp.com/biz/three-twins-ice-cream-san-francisco-5', address:'254 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Tipsy Pig', link:'http://www.yelp.com/biz/the-tipsy-pig-san-francisco-2', address:'2231 Chestnut St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Tonga Room & Hurricane Bar', link:'http://www.yelp.com/biz/tonga-room-and-hurricane-bar-san-francisco', address:'950 Mason St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Tonic', link:'http://www.yelp.com/biz/tonic-san-francisco', address:'2360 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Tony\'s Pizza Napoletana', link:'http://www.yelp.com/biz/tonys-pizza-napoletana-san-francisco', address:'1570 Stockton St', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Toronado', link:'http://www.yelp.com/biz/toronado-san-francisco?osq=lower+haight+bars', address:'547 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Trick Dog', link:'http://www.yelp.com/biz/trick-dog-san-francisco', address:'3010 20th St', city:'San Francisco', state:'CA', zip_code:'94110')
Venue.create(name:'Trou Normand', link:'http://www.yelp.com/biz/trou-normand-san-francisco', address:'140 New Montgomery St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Two Sisters Bar and Books', link:'http://www.yelp.com/biz/two-sisters-bar-and-books-san-francisco', address:'579 Hayes St', city:'San Francisco', state:'CA', zip_code:'94102')
Venue.create(name:'Una Pizza Napoletana', link:'http://www.yelp.com/biz/una-pizza-napoletana-san-francisco', address:'210 11th St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Union Larder', link:'http://www.yelp.com/biz/union-larder-san-francisco', address:'1945 Hyde St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Uva Enoteca', link:'http://www.yelp.com/biz/uva-enoteca-san-francisco', address:'568 Haight St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Verbena', link:'http://www.yelp.com/biz/verbena-san-francisco', address:'2323 Polk St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Vesta', link:'http://www.yelp.com/biz/vesta-redwood-city', address:'2022 Broadway', city:'Redwood City', state:'CA', zip_code:'94063')
Venue.create(name:'Vesuvio', link:'http://www.yelp.com/biz/vesuvio-cafe-san-francisco', address:'255 Columbus Ave', city:'San Francisco', state:'CA', zip_code:'94133')
Venue.create(name:'Vin Vino Wine', link:'http://www.yelp.com/biz/vin-vino-wine-palo-alto-3', address:'437 California Ave', city:'Palo Alto', state:'CA', zip_code:'94306')
Venue.create(name:'Wine Jar', link:'http://www.yelp.com/biz/wine-jar-san-francisco', address:'1870 Fillmore St', city:'San Francisco', state:'CA', zip_code:'94115')
Venue.create(name:'Wine Kitchen', link:'http://www.yelp.com/biz/wine-kitchen-san-francisco?osq=nopa+restaurants', address:'507 Divisadero St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Wooly Pig Cafe', link:'http://www.yelp.com/biz/wooly-pig-cafe-san-francisco', address:'205 Hugo St', city:'San Francisco', state:'CA', zip_code:'94122')
Venue.create(name:'Wrecking Ball Coffee Roasters', link:'http://www.yelp.com/biz/wrecking-ball-coffee-roasters-san-francisco-2', address:'2271 Union St', city:'San Francisco', state:'CA', zip_code:'94123')
Venue.create(name:'Yank Sing', link:'http://www.yelp.com/biz/yank-sing-san-francisco-2', address:'101 Spear St', city:'San Francisco', state:'CA', zip_code:'94105')
Venue.create(name:'Yield Wine Bar', link:'http://www.yelp.com/biz/yield-wine-bar-san-francisco', address:'2490 3rd St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'Zazie', link:'http://www.yelp.com/biz/zazie-san-francisco', address:'941 Cole St', city:'San Francisco', state:'CA', zip_code:'94117')
Venue.create(name:'Zeitgeist', link:'http://www.yelp.com/biz/zeitgeist-san-francisco', address:'199 Valencia St', city:'San Francisco', state:'CA', zip_code:'94103')
Venue.create(name:'Zeki\'s Bar', link:'http://www.yelp.com/biz/zekis-bar-san-francisco', address:'1319 California St', city:'San Francisco', state:'CA', zip_code:'94109')
Venue.create(name:'Zero Zero', link:'http://www.yelp.com/biz/zero-zero-san-francisco?osq=soma+restaurants', address:'826 Folsom St', city:'San Francisco', state:'CA', zip_code:'94107')
Venue.create(name:'ZombieRunner Coffee', link:'http://www.yelp.com/biz/zombierunner-palo-alto-2', address:'429 S California Ave', city:'Palo Alto', state:'CA', zip_code:'94306')
Venue.create(name:'Zushi Puzzle', link:'http://www.yelp.com/biz/zushi-puzzle-san-francisco-2', address:'1910 Lombard St', city:'San Francisco', state:'CA', zip_code:'94123')